gazebo_ros_control/pid_gains:
  front_right_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
  back_right_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
  front_left_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}
  back_left_wheel_joint: {p: 1.0, i: 0.0, d: 1.0}